# Generated by Django 6.0 on 2025-12-19 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0003_remove_employee_user_alter_employee_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loastatus',
            options={'ordering': ['name'], 'verbose_name': 'e-Contract Step', 'verbose_name_plural': 'e-Contract Steps'},
        ),
        migrations.RemoveField(
            model_name='tender',
            name='contract_creator',
        ),
        migrations.RemoveField(
            model_name='tender',
            name='contract_status',
        ),
        migrations.RemoveField(
            model_name='tender',
            name='e_purchase_order_no',
        ),
        migrations.RemoveField(
            model_name='tender',
            name='loa_status',
        ),
        migrations.RemoveField(
            model_name='tender',
            name='sap_purchase_order_no',
        ),
        migrations.AddField(
            model_name='tender',
            name='quarter',
            field=models.CharField(blank=True, choices=[('Q1', 'Quarter 1 (Jul-Sep)'), ('Q2', 'Quarter 2 (Oct-Dec)'), ('Q3', 'Quarter 3 (Jan-Mar)'), ('Q4', 'Quarter 4 (Apr-Jun)')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='reservation',
            field=models.CharField(blank=True, choices=[('AGPO', 'AGPO (Access to Government Procurement Opportunities)'), ('PWD', 'Persons with Disabilities'), ('YOUTH', 'Youth'), ('WOMEN', 'Women'), ('OPEN', 'Open/Not Reserved')], max_length=20, null=True, verbose_name='Reservation (AGPO)'),
        ),
        migrations.AddField(
            model_name='tender',
            name='tender_status',
            field=models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CLOSED', 'Closed'), ('UNDER_EVALUATION', 'Under Evaluation'), ('EVALUATED', 'Evaluated'), ('AWARDED', 'Awarded'), ('CANCELLED', 'Cancelled')], max_length=20, null=True, verbose_name='Tender Status'),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_reference', models.CharField(blank=True, help_text='Contract reference number', max_length=100, null=True)),
                ('e_purchase_order_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='e-Purchase Order No')),
                ('sap_purchase_order_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='SAP Purchase Order No')),
                ('supplier_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Name of Supplier Awarded')),
                ('supplier_county', models.CharField(blank=True, max_length=100, null=True, verbose_name='County of Origin')),
                ('contract_signature_date', models.DateField(blank=True, null=True, verbose_name='Contract Signature Date')),
                ('contract_expiry_date', models.DateField(blank=True, null=True, verbose_name='Contract Expiry Date')),
                ('contract_duration', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contract Duration')),
                ('contract_delivery_period', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contract Delivery Period')),
                ('contract_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tender_security_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tender_security_expiry_date', models.DateField(blank=True, null=True)),
                ('performance_security_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('performance_security_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('performance_security_expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract_creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contracts', to='tenders.employee')),
                ('contract_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='tenders.contractstatus')),
                ('loa_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='tenders.loastatus', verbose_name='e-Contract Step')),
                ('tender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='tenders.tender')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractCITCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, help_text='e.g., Chairperson, Inspector, Acceptance Officer', max_length=100, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cit_committee_members', to='tenders.contract')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cit_committees', to='tenders.employee')),
            ],
            options={
                'verbose_name': 'CIT/Inspection & Acceptance Committee Member',
                'verbose_name_plural': 'CIT/Inspection & Acceptance Committee Members',
                'unique_together': {('contract', 'employee')},
            },
        ),
    ]
