# Generated by Django 6.0 on 2026-01-22 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0004_alter_loastatus_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tender',
            name='department',
        ),
        migrations.RemoveField(
            model_name='tender',
            name='requisition_number',
        ),
        migrations.RemoveField(
            model_name='tender',
            name='section',
        ),
        migrations.RemoveField(
            model_name='tender',
            name='shopping_cart',
        ),
        migrations.RemoveField(
            model_name='tender',
            name='user',
        ),
        migrations.AddField(
            model_name='tender',
            name='tender_evaluation_duration_days',
            field=models.PositiveIntegerField(blank=True, help_text='Evaluation duration in days', null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='tender_evaluation_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='tender_opening_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='tender_opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='tender_validity_duration_days',
            field=models.PositiveIntegerField(blank=True, help_text='Validity period in days', null=True),
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisition_number', models.CharField(max_length=100, unique=True)),
                ('shopping_cart', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requisitions', to='tenders.employee', verbose_name='Assigned User')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions', to='tenders.department')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions', to='tenders.division')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions', to='tenders.section')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='tender',
            name='requisition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenders', to='tenders.requisition'),
        ),
    ]
