# Generated by Django 6.0 on 2026-01-22 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0005_remove_tender_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tender',
            name='region',
        ),
        migrations.AddField(
            model_name='requisition',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions', to='tenders.region'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requisitions', to='tenders.employee', verbose_name='Requisition Owner'),
        ),
    ]
