# Generated by Django 6.0 on 2026-02-17 18:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('tenders', '0006_remove_tender_region_requisition_region_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='tender_security_value',
            new_name='tender_security_amount',
        ),
        migrations.RenameField(
            model_name='tender',
            old_name='tender_validity_duration_days',
            new_name='tender_validity_days',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='contract_reference',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='contract_signature_date',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='loa_status',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='performance_security_duration',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='supplier_county',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='supplier_name',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='requisition_number',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='shopping_cart',
        ),
        migrations.RemoveField(
            model_name='tender',
            name='egp_tender_reference',
        ),
        migrations.RemoveField(
            model_name='tender',
            name='kengen_tender_reference',
        ),
        migrations.RemoveField(
            model_name='tender',
            name='procurement_type',
        ),
        migrations.RemoveField(
            model_name='tender',
            name='quarter',
        ),
        migrations.RemoveField(
            model_name='tender',
            name='reservation',
        ),
        migrations.RemoveField(
            model_name='tender',
            name='tender_evaluation_duration',
        ),
        migrations.RemoveField(
            model_name='tender',
            name='tender_status',
        ),
        migrations.AddField(
            model_name='contract',
            name='commencement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_delivery_period_measure',
            field=models.CharField(blank=True, choices=[('DAYS', 'Days'), ('MONTHS', 'Months'), ('YEARS', 'Years')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_duration_measure',
            field=models.CharField(blank=True, choices=[('DAYS', 'Days'), ('MONTHS', 'Months'), ('YEARS', 'Years')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_step',
            field=models.CharField(blank=True, choices=[('ION', 'Intention of Notification'), ('LOA', 'Letter of Award'), ('ARB', 'ARB Decision'), ('DRAFT', 'Draft Contract'), ('FINAL', 'Final Contract')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='contractor_supplier',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contract_records', to='tenders.employee'),
        ),
        migrations.AddField(
            model_name='contract',
            name='performance_security_duration_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='responsibility',
            field=models.CharField(blank=True, choices=[('CONTRACT_CREATOR', 'Contract Creator'), ('SUPPLIER', 'Supplier'), ('LEGAL', 'Legal'), ('HOP', 'Head of Procurement'), ('AO', 'Accounting Officer'), ('TENDER_CREATOR', 'Tender Creator')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='tender_security_validity_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractcitcommittee',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cit_committee_members', to='tenders.employee'),
        ),
        migrations.AddField(
            model_name='contractstatus',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contract_statuses', to='tenders.employee'),
        ),
        migrations.AddField(
            model_name='department',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_departments', to='tenders.employee'),
        ),
        migrations.AddField(
            model_name='division',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_divisions', to='tenders.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_employees', to='tenders.employee'),
        ),
        migrations.AddField(
            model_name='loastatus',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_loa_statuses', to='tenders.employee'),
        ),
        migrations.AddField(
            model_name='procurementtype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_procurement_types', to='tenders.employee'),
        ),
        migrations.AddField(
            model_name='region',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_regions', to='tenders.employee'),
        ),
        migrations.AddField(
            model_name='requisition',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_requisitions', to='tenders.employee'),
        ),
        migrations.AddField(
            model_name='requisition',
            name='creation_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requisition',
            name='date_assigned',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requisition',
            name='e_requisition_no',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, unique=True, verbose_name='e-Requisition No'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requisition',
            name='procurement_type',
            field=models.CharField(choices=[('TENDER', 'Tender'), ('QUOTATION', 'Quotation')], default='TENDER', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requisition',
            name='requisition_description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requisition',
            name='shopping_cart_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requisition',
            name='shopping_cart_no',
            field=models.PositiveBigIntegerField(default=21),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requisition',
            name='shopping_cart_status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending'), ('BUDGET_ISSUE', 'Budget Issue')], default=32, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requisition',
            name='tender_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisition_tender_creations', to='tenders.employee'),
        ),
        migrations.AddField(
            model_name='section',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sections', to='tenders.employee'),
        ),
        migrations.AddField(
            model_name='tender',
            name='agpo_category',
            field=models.CharField(blank=True, choices=[('PLWD', 'PLWD'), ('YOUTH', 'Youth'), ('WOMEN', 'Women')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tender_records', to='tenders.employee'),
        ),
        migrations.AddField(
            model_name='tender',
            name='eligibility',
            field=models.CharField(choices=[('INTERNATIONAL', 'Open International'), ('NATIONAL', 'Open National'), ('CITIZEN_CONTRACTOR', 'Citizen Contractor'), ('AGPO', 'AGPO')], default='INTERNATIONAL', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tender',
            name='procurement_method',
            field=models.CharField(blank=True, choices=[('OPEN_TENDER', 'Open Tender'), ('RESTRICTED_TENDER', 'Restricted Tender'), ('REQUEST_FOR_QUOTATION', 'Request for Quotation'), ('DIRECT_PROCUREMENT', 'Direct Procurement'), ('REQUEST_FOR_PROPOSAL', 'Request for Proposal'), ('EXPRESSION_OF_INTEREST', 'Expression of Interest'), ('PREQUALIFICATION', 'Pre-Qualification'), ('FRAMEWORK', 'Framework')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='proposed_advert_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='tender_approval_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('CLARIFICATION_REQUESTED', 'Clarification Requested')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='tender_creation_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tender',
            name='tender_reference_number',
            field=models.CharField(default=536373, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tender',
            name='tender_step',
            field=models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('EVALUATION', 'Evaluation'), ('NEGOTIATION', 'Negotiation'), ('CANCELLED', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tenderevaluationcommittee',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_evaluation_committee_members', to='tenders.employee'),
        ),
        migrations.AddField(
            model_name='tenderopeningcommittee',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_opening_committee_members', to='tenders.employee'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_user_profiles', to='tenders.employee'),
        ),
        migrations.RunSQL(
            """
            UPDATE tenders_contract
            SET contract_duration = NULLIF(regexp_replace(contract_duration, '\\D.*$', ''), '')
            WHERE contract_duration IS NOT NULL;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            """
            UPDATE tenders_contract
            SET contract_delivery_period = NULLIF(regexp_replace(contract_delivery_period, '\\D.*$', ''), '')
            WHERE contract_delivery_period IS NOT NULL;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_delivery_period',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='e_purchase_order_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='eGP Purchase Order No'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='tender_id',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_countries', to='tenders.employee')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='country_of_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='tenders.country'),
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_currencies', to='tenders.employee')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='tenders.currency'),
        ),
    ]
