# Generated by Django 6.0 on 2026-02-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0007_rename_tender_security_value_contract_tender_security_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractcitcommittee',
            name='role',
            field=models.CharField(blank=True, choices=[('MEMBER', 'Member'), ('CHAIR', 'Chair'), ('SECRETARY', 'Secretary')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tenderevaluationcommittee',
            name='role',
            field=models.CharField(blank=True, choices=[('MEMBER', 'Member'), ('CHAIR', 'Chair'), ('SECRETARY', 'Secretary')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tenderopeningcommittee',
            name='role',
            field=models.CharField(blank=True, choices=[('MEMBER', 'Member'), ('CHAIR', 'Chair'), ('SECRETARY', 'Secretary')], max_length=20, null=True),
        ),
    ]
