# Generated by Django 6.0 on 2026-02-19 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0008_alter_contractcitcommittee_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tender',
            name='estimated_value',
        ),
    ]
