# Generated by Django 6.0 on 2026-02-19 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0009_remove_procurementtype'),
        ('tenders', '0009_remove_tender_estimated_value'),
    ]

    operations = [
    ]
