# Generated by Django 6.0 on 2026-02-19 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0010_merge_20260219_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requisitions', to='tenders.employee', verbose_name='Owner(DO)'),
        ),
    ]
